management:
security:
    jwt:
        token:
            secret-key: secret-key
            expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UtilisateurRessource:
    signin: Authenticates user and returns its JWT token.
    signup: Creates user and returns its JWT token
    delete: Deletes specific user by username
    search: Returns specific user by username
    me: Returns current user's data


spring:
    main:
        allow-bean-definition-overriding: true

    application:
        name: workflow-core
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jackson:
        serialization:
            write-dates-as-timestamps: true
    liquibase:
        default-schema: dbo
        enabled: false
        change-log: classpath:data/changelog-master.xml
    output:
        ansi:
            enabled: ALWAYS

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:sqlserver://DESKTOP-68HJIHD;databaseName=pfe;trustServerCertificate=true;encrypt=false;
        username: sa
        password: 123
        encrypt: false


    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
            #            ddl-auto: create
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.default_schema: dbo
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: hazelcast
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
            org.hibernate.envers.store_data_at_delete: true
    mail:
        username: ehadrich914@gmail.com
        password: azxy isgp wonj dwhy
        host: smtp.gmail.com
        port: 465
        properties:
            mail:
                smtp:
                    connectiontimeout: 3000
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        enable: true

    profiles:
        include: no-liquibase, secure-jwt
    config:
        use-legacy-processing: true
lang:
    secondary: ar

server:
    servlet:
        contextPath: /workflow-core
    port: 9011
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


hystrix:
    command.default.execution.isolation.strategy: THREAD

email:
    from: marwen.hadrich@csys.com.tn
    to: marwen.hadrich@csys.com.tn


